export const IS_ERROR = 'IS_ERROR';
export const IS_LOADING = 'IS_LOADING';

// PRODCUTS ACTIONS

export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

// CART ACTIONS

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const RESET_CART = 'RESET_CART';
export const INCREMENT_QTY = 'INCREMENT_QTY';
export const DECREMENT_QTY = 'DECREMENT_QTY';
